[tool.poetry]
name = "test-ing-algo"
version = "0.1.0"
description = ""
authors = ["AlvaroRDP.pr <alvarordp.pr@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
